# Generated by Django 5.2.12 on 2026-04-09 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FetchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('canonical_slug', models.TextField(db_index=True)),
                ('context_length', models.IntegerField(blank=True, null=True)),
                ('input_modalities', models.JSONField(default=list)),
                ('output_modalities', models.JSONField(default=list)),
                ('pricing_completion', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('pricing_prompt', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('pricing_image', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('pricing_request', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('fetch_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='calculator.fetchrun')),
            ],
            options={
                'indexes': [models.Index(fields=['fetch_run', 'canonical_slug'], name='calculator__fetch_r_2d022a_idx')],
            },
        ),
    ]
